### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by vverma022** [vverma022/model-merge#13]
Add user authentication

**Comment by cpwallah** [comment]
assign this to me @vverma022

**Comment by vverma022** [comment]
> assign this to me @vverma022

Sure, 
- Prisma is already setup with a PostgresSQL database in the backend 
- A User model is already created 
- Only implement the backend and document everything so that the frontend can be setup accordingly.

**Comment by vverma022** [comment]
<img width="1425" alt="Screenshot 2024-07-24 at 10 47 37 PM" src="https://github.com/user-attachments/assets/3516bd39-034e-4b1f-b6c8-a80ac6745ad0">
<img width="1425" alt="Screenshot 2024-07-24 at 10 47 46 PM" src="https://github.com/user-attachments/assets/3b24cbc5-dddb-468a-b018-2beff18e8181">
The Sign-in and Signup component have been added. Please take that into notice and implement User Auth at the backend. User should be routed to Sign-in or Sign-up page from the welcome page.
 @cpwallah

**Comment by vverma022** [comment]
Any Update @cpwallah  ?
