### ISSUE TITLE
Fix Animation Render 

### ISSUE THREAD

**Issue by vverma022** [vverma022/model-merge#6]
When user enters a prompt the typewriter animation is used to display the output. The animation is taking the whole height to render in the component. 

https://github.com/user-attachments/assets/649eabe5-83ab-4a7c-a14a-a7b554e5808a

**Comment by NatsuDrag9** [comment]
Please assign the issue to me. I'd like to solve it.

**Comment by vverma022** [comment]
Sure. Do explain the approach so that it is easier to understand.

**Comment by vverma022** [comment]
> Please assign the issue to me. I'd like to solve it.

Sure. Do explain the approach so that it is easier to understand.

**Comment by NatsuDrag9** [comment]
I've not really thought about the solution yet. Currently, I'm facing issues in setting up the project.
Why is `node_modules` included in the `backend/`? As far as I know, node_modules is added in `.gitignore` and is usually not pushed to the repo.

**Comment by vverma022** [comment]
> I've not really thought about the solution yet. Currently, I'm facing issues in setting up the project.
> 
> Why is `node_modules` included in the `backend/`? As far as I know, node_modules is added in `.gitignore` and is usually not pushed to the repo. 

I'll resolve it. Thank you for pointing that out.

**Comment by NatsuDrag9** [comment]
> > I've not really thought about the solution yet. Currently, I'm facing issues in setting up the project.
> > Why is `node_modules` included in the `backend/`? As far as I know, node_modules is added in `.gitignore` and is usually not pushed to the repo.
> 
> I'll resolve it. Thank you for pointing that out.

Sure, no issue. 
Despite adding node_modules to `backend/.gitignore`, I'm unable to resolve it at my end. Not sure what's the problem.

**Comment by vverma022** [comment]
> > > I've not really thought about the solution yet. Currently, I'm facing issues in setting up the project.
> 
> > > Why is `node_modules` included in the `backend/`? As far as I know, node_modules is added in `.gitignore` and is usually not pushed to the repo.
> 
> > 
> 
> > I'll resolve it. Thank you for pointing that out.
> 
> 
> 
> Sure, no issue. 
> 
> Despite adding node_modules to `backend/.gitignore`, I'm unable to resolve it at my end. Not sure what's the problem.

Please ensure the backend is setup correctly.
- .env file with API keys for Groq 
- The issue is primarily on the frontend bit of the project. 
- Check the search component, main component and the index.css file where the control of the animation is defined.

**Comment by NatsuDrag9** [comment]
Sorry, I wasn't clear about my problem.
The issue that I am facing right now concerns with node_modules not being ignored despite adding `node_modules` to `backend/.gitignore` file. As the new files in `node_modules` are being tracked by git, I can't make a _sensible_ commit.

**Comment by vverma022** [comment]
Try creating a branch and solve both the issues.

**Comment by NatsuDrag9** [comment]
Ok, will do that.

**Comment by vverma022** [comment]
> Ok, will do that.

I'll assign it to you. Thank you

**Comment by NatsuDrag9** [comment]
> I'll assign it to you. Thank you

Sure

**Comment by vverma022** [comment]
>  
> 
> > I'll assign it to you. Thank you
> 
> 
> 
> Sure

Please comment on the issue to be assigned.

**Comment by NatsuDrag9** [comment]
> > > I'll assign it to you. Thank you
> > 
> > 
> > Sure
> 
> Please comment on the issue to be assigned.

Commented

**Comment by NatsuDrag9** [comment]
Changing the ```.typewriter-container``` and its corresponding animations in ```index.css``` did not solve the bug. The issue was related to Tailwind's ```animate-typing``` class and the custom ```wrap``` class. I couldn't exactly pinpoint the bug. Instead, I made some changes to the the text rendering logic in ```useEffect```. Instead of ```setTimer```, I'm using ```setInterval``` based on this [reference](https://dev.to/stiaanwol/how-to-build-the-chatgpt-typing-animation-in-react-2cca).

The output which is shown below.

https://github.com/user-attachments/assets/125e4d2a-cb9c-4c05-a1bb-0b7f87dd3065

Let me know if this is works so that I can create a pull request.

**Comment by vverma022** [comment]
Please make a pull request.

**Comment by NatsuDrag9** [comment]
I created two pull requests. After accepting the pull requests, please close this issue.
