### ISSUE TITLE
Node Modules in Backend 

### ISSUE THREAD

**Issue by vverma022** [vverma022/model-merge#7]
Sorry, I wasn't clear about my problem.
The issue that I am facing right now concerns with node_modules not being ignored despite adding `node_modules` to `backend/.gitignore` file. As the new files in `node_modules` are being tracked by git, I can't make a _sensible_ commit.

_Originally posted by @NatsuDrag9 in https://github.com/vverma022/model-merge/issues/6#issuecomment-2229964559_

**Comment by NatsuDrag9** [comment]
Assign this issue to me. I'll resolve it.

**Comment by NatsuDrag9** [comment]
A few queries:

**Image 1**
![image](https://github.com/user-attachments/assets/d324ab86-ac6c-4fc3-a97f-4a13f56b93a0)

**Image 2**
![image](https://github.com/user-attachments/assets/48d7bd67-01d2-40df-aba6-e76948db96af)

1. Is it ```Groq``` or ```Grow``` in the image 1?
2. The case of the api keys mentioned in readme (refer image 2) do not match the case of environment variables used in ```routes/ai_model_name.js```. For example, the readme mentions ```Cohere_API_Key``` while [cohere.js](https://github.com/vverma022/model-merge/blob/main/backend/routes/cohere.js) uses ```COHERE_API_KEY```. I've fixed this bug locally on my pc but haven't pushed it yet. If you're ok, I'll push it in the same branch that addresses this issue on _node-modules?_
3. [groq.js](https://github.com/vverma022/model-merge/blob/main/backend/routes/groq.js) uses ```LLAMA_API_KEY``` but the readme file mentions ```Groq_API_Key```.  What to do about this?
4. Do I need to create api keys for other routes that are not mentioned in the readme file?

**Comment by vverma022** [comment]
The Readme needs to be edited. Please use the variable names in the code base. I have not updated the readme.

**Comment by NatsuDrag9** [comment]
> The Readme needs to be edited. Please use the variable names in the code base. I have not updated the readme.

This answers the first three questions. What about question 4? Also, can you share the link to generate the api key for the env variable AI_ML_API_KEY?

**Comment by vverma022** [comment]
> > The Readme needs to be edited. Please use the variable names in the code base. I have not updated the readme.
> 
> 
> 
> This answers the first three questions. What about question 4? Also, can you share the link to generate the api key for the env variable AI_ML_API_KEY?

Not integrated in the application as of now. But for reference https://aimlapi.com/app/sign-up/

**Comment by NatsuDrag9** [comment]
> > > The Readme needs to be edited. Please use the variable names in the code base. I have not updated the readme.
> > 
> > 
> > This answers the first three questions. What about question 4? Also, can you share the link to generate the api key for the env variable AI_ML_API_KEY?
> 
> Not integrated in the application as of now. But for reference https://aimlapi.com/app/sign-up/

Understood.

**Comment by NatsuDrag9** [comment]
Just to be sure, is [this](https://www.llama-api.com/) the link to llama api?

**Comment by vverma022** [comment]
> Just to be sure, is [this](https://www.llama-api.com/) the link to llama api?

https://groq.com

**Comment by NatsuDrag9** [comment]
The [package.json](https://github.com/vverma022/model-merge/blob/main/frontend/package.json) in ```frontend/``` does not have the ```start``` script. How do I run the frontend of the application?

**Comment by vverma022** [comment]
> The [package.json](https://github.com/vverma022/model-merge/blob/main/frontend/package.json) in ```frontend/``` does not have the ```start``` script. How do I run the frontend of the application?

Npm i to install the dependencies 
And then you can run npm run dev.

**Comment by NatsuDrag9** [comment]
I've updated the readme on my [branch](https://github.com/NatsuDrag9/model-merge/tree/node_modules-bug-fix). Review it

**Comment by NatsuDrag9** [comment]
By the way, I fixed this  ```backend/node_modules``` issue. I just tested the application on my local pc and it is working fine. Shall I merge it into main on my fork and then create a pull request?

**Comment by vverma022** [comment]
Please create a pull request.

**Comment by NatsuDrag9** [comment]
I created a pull request. Review and let me know regarding any changes.

**Comment by NatsuDrag9** [comment]
Since you merged the pull request, I think this issue can be closed now.
